site_name: CSS Extension for DITA-OT

repo_url: https://github.com/jason-fox/fox.jason.extend.css
repo_name: GitHub

pages:
    -  Home: index.md
    - 'Install' : 'install.md'
    - 'Usage' : 'usage.md'

theme: readthedocs
extra_css: ["https://jason-fox.github.io/fox.jason.extend.css/dita.css"]