name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Run DITA-OT Unit Test
        uses: jason-fox/dita-unit-test-action@master
        with:
          dita-ot-version: '4.0'
          plugin: 'fox.jason.extend.css'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results.html
